config:
  roles_path:
  - "~/.ansible/roles"
  - "/usr/share/ansible/roles"
  - "/etc/ansible/roles"
  - "/usr/local/src/ansible/roles"

  collections_paths:
  - "~/.ansible/collections"
  - "/usr/share/ansible/collections"

ansible_config:
    interpreter_python: "auto_silent"
    host_key_checking: "False"
    remote_user: "{{default_user}}"
    private_key_file: "/home/{{default_user}}/.ssh/vagrant.pem"
    roles_path: "{{ config.roles_path | join(':') }}"
    collections_paths: "{{ config.collections_paths | join(':') }}"
